name: CD
on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/test.yaml
    needs: [build]
    secrets: inherit

  build-push-image:
    name: Build & Push Image
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker Build
        run: docker build --platform linux/amd64 -t ruegerj/monkey-playground:${{github.event.release.tag_name}} .

      - name: Docker Push
        run: |
          docker tag ruegerj/monkey-playground:${{github.event.release.tag_name}} ghcr.io/ruegerj/monkey-playground:${{github.event.release.tag_name}}
          docker push ghcr.io/ruegerj/monkey-playground:${{github.event.release.tag_name}}
          docker tag ghcr.io/ruegerj/monkey-playground:${{github.event.release.tag_name}} ghcr.io/ruegerj/monkey-playground:latest
          docker push ghcr.io/ruegerj/monkey-playground:latest
